stages:
  prepare:
    cmd: python src/prepare.py data/train/text.txt data/train/labels.txt
    params:
    - prepare.seed
    - prepare.val_split

    deps:
    - src/prepare.py
    - data/train/text.txt
    - data/train/labels.txt
  augment:
    cmd: python src/augment.py data/prepared/train data/augmented/train
    params:
    - augment.seed
    - augment.use_sample
    - augment.use_augment
    - augment.stopwords
    - augment.aug_max
    - augment.proportion
    deps:
    - src/augment.py
    - data/prepared/train/X_train.csv
    - data/prepared/train/y_train.csv
  train:
    cmd: python src/train.py data/augmented/train/X_train.csv data/augmented/train/y_train.csv data/prepared/val/X_val.csv data/prepared/val/y_val.csv
    params:
    - train.epochs
    - train.lr
    - train.batch_size
    deps:
    - src/train.py
    - data/augmented/train/X_train.csv 
    - data/augmented/train/y_train.csv 
    - data/prepared/val/X_val.csv 
    - data/prepared/val/y_val.csv
  evaluate:
    cmd: python src/evaluate.py data/test/text.txt data/test/labels.txt scores/scores.json
    params:
    - evaluate.batch_size
    deps:
    - src/evaluate.py
    - data/test/text.txt
    - data/test/labels.txt
    - model.pth
    metrics:
    - scores/scores.json:
        cache: false