prepare:
  seed: 2137
  val_split: 0.2
augment:
  use_sample: False
  use_augment: False
  stopwords:
  aug_max: 2
  proportion: 1
  seed: 2137
train:
  epochs: 1
  lr: 0.00001
  batch_size: 4
evaluate:
  batch_size: 32
